### ISSUE TITLE
i can ask you? similar control 4 way for vertices in mesh for blender..? (dont know name title technical)

### ISSUE THREAD

**Issue by manuelsongokuh** [mifth/mifthtools#12]
hello

you can see before video link: https://vimeo.com/15356250
 time: 1:46 to 2:09
this is VERY HELPFULLY like as bezeir point of corner:
![image-link-inkscape](http://tavmjong.free.fr/INKSCAPE/MANUAL/images/PATHS/Bezier3.png)

**Comment by manuelsongokuh** [comment]
see my video explain:
https://mega.nz/#!uw8V0YyB!l3KkNmSe93qbly1jUAHoQpzlJ1dpvJRto4AvDe8t3ys


https://mega.nz/#!Gs8RmLKL!m-EcfYsFu1iJrpq1fVxlrIm8fe4S-D5uEofrMUSYYjc

target to mesh editing..

**Comment by mifth** [comment]
Hi.

Thanks for videos. It's a good tool for modeling. But this is a very complex tool. Not for python.
Blender developers should do such a tool.

**Comment by manuelsongokuh** [comment]
yes..i did send them develops blender, but they said to send you miratools...so i'm write here.. i did try send them but they are not respond me.. you can send or re-contact .. i dont know what i will do..
thank you for respond me..

**Comment by mifth** [comment]
Oooo! Blender developers point you to me? Hehe.. Actually, they have never contact me. :)

Sorry, this is really a complex too. The devs should do this.

**Comment by manuelsongokuh** [comment]
ok, nice to meet you.
