### ISSUE TITLE
clone draw error

### ISSUE THREAD

**Issue by andrehunter** [mifth/mifthtools#16]
I installed mithtools, but when I try clonedraw to run it on blender it presents malfunctions, how to solve the problem?

LINK: https://www.youtube.com/watch?v=2K-doI6KIeM&feature=youtu.be﻿
![mithtools problem](https://cloud.githubusercontent.com/assets/18272681/17080932/4eff2260-5119-11e6-9813-82f3df9ffd26.png)

#

**Comment by mifth** [comment]
Hi.
You need blender 2.77 to run the clone draw tool. Blender developers changed some things during new version releases.

**Comment by mifth** [comment]
I close this issue. I hope you installed Blender 2.77 and everything is ok. )

**Comment by andrehunter** [comment]
ok , thanks

2016-07-24 17:05 GMT-03:00 mifth <notifications@github.com>:
