### ISSUE TITLE
Mifthtools does not install

### ISSUE THREAD

**Issue by isohedron** [mifth/mifthtools#22]
I am having difficulty installing the mifthtools package.  I unzipped the folder into the blender addons directory. For some reason the addon doesn't show up in the user preferences. 

My version of Blender is 2.78a

**Comment by mifth** [comment]
Hi.
Did you try this?

Installation:
- download the archive from master
- unzip it
- copy "mifth_tools/blender/addons/mifth_tools" folder into your blender's scripts folder.

**Comment by mkbreuer** [comment]
...or...   (instead of copy and paste)

- create a zip of the mifth_tools folder 
- and install it over user preferences

**Comment by enzyme69** [comment]
Apparently the zipped contains lots more other stuffs not related to Blender, like Houdini, etc. But I copy paste into a folder where the add ons should be, restart Blender and there you go.

**Comment by fabriciomira** [comment]
Ctrl+Alt+U and under the search field is the "Supported Level". Choose "Testing" and the addon will appear.

**Comment by mifth** [comment]
Thanks. I close this issue.
