### ISSUE TITLE
Merge linear deformer for curve for mira_tools

### ISSUE THREAD

**Issue by JoseConseco** [mifth/mifthtools#24]
I made linear deformer that work for curve objects. Are there any chances you could put it into master?
Here are the files:
https://github.com/JoseConseco/mira_tools/
Only two files were changed compared to master:
- **mi_linear_deformer_curve**.py  - new file (same as **mi_linear_deformer**.py but works on curve)
- **mi_widget_linear_deform**.py  - new function was added  - **get_tool_verts_curv**  (based on **get_tool_verts**)
That is it. I didn't add it to ui. Not sure where to place it, maybe make it so that if you perform operation on mesh then use old linear deformer, and if operation is performed on curve the use new lin deformer?

**Comment by mifth** [comment]
Hello!

Thank you for your contribution? I have some questions.
Are you sure that this is very useful for curves? I have never had such need to bend points at the cuve. )

**Comment by JoseConseco** [comment]
I would say, it is the best way to model curves :). Here is example of how it can be used:
https://youtu.be/gtbhmYEKGZE?t=583

I also modified file: init.py - appended linear_deformer button to  VIEW3D_PT_tools_curveedit panel.
Thanks for great addon.

**Comment by mifth** [comment]
Ok, I'll add curves support. Give me some time, please.
I'll try to add it at weekends.

**Comment by mifth** [comment]
Is this issue fixed in MT3?

**Comment by JoseConseco** [comment]
the: mi_linear_deformer_curve.py is already included in blender 2.8 version. Works same as on mesh, except it is using curve points
This can be closed

**Comment by mifth** [comment]
Great. Thank you!
