### ISSUE TITLE
Please add support for Blender 2.80

### ISSUE THREAD

**Issue by nonameplum** [mifth/mifthtools#25]
Blender 2.80 is currently in Beta phase and API is almost stable. We should not expect any big changes anymore. It would be great if we could add support for this awesome plugin to Blender 2.80 as there is already a lot of users using it.

**Comment by mifth** [comment]
Yep, i know. i'll do it when i find some free time.

**Comment by Almaz** [comment]
Please, do it!

**Comment by mifth** [comment]
Very soon.

**Comment by Almaz** [comment]
Hi there! Is it ready for use in Blender 2.8?

**Comment by mifth** [comment]
Hi. Not yet.

**Comment by Almaz** [comment]
It will be only after the release of 2.8?

**Comment by mifth** [comment]
It depends on the free time. New job, freelance and family take all the time )
All will be ported. Be sure.
