### ISSUE TITLE
Error in MiraTools

### ISSUE THREAD

**Issue by SimonMiller3D** [mifth/mifthtools#28]
Hi.

I am getting an error with Mira tools. I am trying to Draw Extrude on a surface:

bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 1 object(s)
bpy.ops.mesh.primitive_uv_sphere_add(radius=1, enter_editmode=False, location=(0, 0, 0))
bpy.ops.object.editmode_toggle()
bpy.ops.mesh.select_mode(use_extend=False, use_expand=False, type='FACE')
bpy.ops.mesh.duplicate_move(MESH_OT_duplicate={"mode":1}, TRANSFORM_OT_translate={"value":(0, 0, 0), "orient_type":'GLOBAL', "orient_matrix":((0, 0, 0), (0, 0, 0), (0, 0, 0)), "orient_matrix_type":'GLOBAL', "constraint_axis":(False, False, False), "mirror":False, "use_proportional_edit":False, "proportional_edit_falloff":'SMOOTH', "proportional_size":1, "use_proportional_connected":False, "use_proportional_projected":False, "snap":False, "snap_target":'CLOSEST', "snap_point":(0, 0, 0), "snap_align":False, "snap_normal":(0, 0, 0), "gpencil_strokes":False, "cursor_transform":False, "texture_space":False, "remove_on_cancel":False, "release_confirm":False, "use_accurate":False})
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.data.window_managers["WinMan"].mirawindow.display_mira_modify = True
bpy.data.window_managers["WinMan"].mirawindow.display_mira_settings = True
bpy.context.scene.mi_settings.surface_snap = True
bpy.ops.mira.draw_extrude()
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\mira_tools\mi_draw_extrude.py", line 308, in modal
    best_obj, hit_normal, hit_position = ut_base.get_mouse_raycast(context, self.picked_meshes, m_coords)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\mira_tools\mi_utils_base.py", line 65, in get_mouse_raycast
    obj, matrix, view_vector, ray_origin, ray_max)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\addons\mira_tools\mi_utils_base.py", line 103, in obj_raycast
    hit_result, hit, normal, face_index = obj.ray_cast(ray_origin_obj, ray_direction_obj, distance=ray_max)
RuntimeError: Error: Object 'Sphere.001' has no evaluated mesh data

location: <unknown location>:-1

**Comment by mifth** [comment]
Could you please send the blend file so that i could repeat the issue?

**Comment by SimonMiller3D** [comment]
Hi

 

File attached the file but It’s nothing special. This is the first time I have used these tools so probably something to do with my installation, but the addon looks amazing and I’m very keen to find out what’s wrong

 

Thanks

**Comment by mifth** [comment]
I see no file. )
May be this guide will help.
https://www.youtube.com/watch?v=h5k91l5EodE

**Comment by SimonMiller3D** [comment]
Great thank you

 

No idea what I was doing wrong before but now works fine.

 

All the best

**Comment by mifth** [comment]
Closed
