### ISSUE TITLE
Mira Primitives make system freeze

### ISSUE THREAD

**Issue by Brad63** [mifth/mifthtools#31]
When I try to add a mira primitive, I get the following message

ORIENT FALSE
MEDIAN CENTER FALSE
CENTER IS 3D CURSOR FALSE

The menus don't work. Nothing works and the only way to shut down Blender is via the Task Manager.

**Comment by mifth** [comment]
Hello,
Could you please add the blend file to reproduce the issue?

**Comment by mifth** [comment]
I guess you did not know how to use the tool. Just Leftclick and right click. )
I close the issue.
