### ISSUE TITLE
Update for Blender 2.91?

### ISSUE THREAD

**Issue by maxim1967** [mifth/mifthtools#33]
Planning an update for Blender 2.91?

**Comment by mifth** [comment]
Could you say what does not work, please?
All should work except to draw clones only. 
Blender 2.91 has a bug according to draw clones. It was fixed in 2.92.

**Comment by maxim1967** [comment]
I don't seem to see any other problems. Only with draw clones. Thank you for the clarification, I will wait for the release of 2.92.
