### ISSUE TITLE
Python Error with Make Arc tool

### ISSUE THREAD

**Issue by Davexx** [mifth/mifthtools#37]
Hello,
I created a square plane on the X and Y axis, subdivided it twice in Edit Mode. then selected an edge loop on the -X axis, then clicked on the Make Arc tool and I get the following error:

```
Python: Traceback (most recent call last):
File "...\3.6\scripts\addons\mira_tools\mi_make_arc.py", line 127, in execute
if isinstance(bm.select_history[0], bmesh.types.BMVert):
IndexError: BMElemSeq[index]: index 0 out of range
```
If I try a similar operation on a 3D cube, selecting a subdivided edge of the object and then click on the Make Arc tool, it seems to work.
I did not find much documentation on the Make Arc tool, so perhaps I am not using it as intended.   

Could you fix the error and perhaps include some more detailed documentation for the tool?

Thanks,
Davexx

**Comment by mifth** [comment]
Hi, could you please provide a blend file and steps to reproduce?

**Comment by Davexx** [comment]
### Steps to produce:
1. New blender scene, top orthographic view.
2. SHFT+A > MiraPrimitives > MiraPlane
3. Edit Mode > Edge Select > CTRL+R add some loop cuts.
4. **Box Select** outside edge (either left, right, top or bottom)
5. Press Make Arc
6. ERROR

1. New blender scene, top orthographic view.
2. SHFT+A > MiraPrimitives > MiraPlane
3. Edit Mode > Edge Select > CTRL+R add some loop cuts.
4. **shift-click select** Edges to compound an outside edge (either left, right, top or bottom).
5. Press Make Arc
6. SUCCESS!

Let me know if you have any questions.
[Make Arc Error.zip](https://github.com/mifth/mifthtools/files/13243037/Make.Arc.Error.zip)

**Comment by mifth** [comment]
Thanks. Could you please try to make one point active after "4" and try again. There should be at least one active point I think.

**Comment by Davexx** [comment]
Ah, okay, yes.  An active vertex or edge in as selection does not cause the error.
Is that one documented somewhere?

**Comment by mifth** [comment]
I didn't document it unfortunately. It's actually something to be fixed. But I didn't find a way to do it yet.

**Comment by Davexx** [comment]
Well, thank you for helping me.  I appreciate it!  
I understand that you may not have a way to fix it yet.  I am a terrible coder, so I have great respect for anyone who can make a functional and valuable tool.
Perhaps just a note in the Wiki to explain to folks looking for a solution?
