### ISSUE TITLE
object mode/wrap object error

### ISSUE THREAD

**Issue by YHOOOO996** [mifth/mifthtools#38]
bpy.data.window_managers["WinMan"].addon_search = "edit"
bpy.ops.object.modifier_add(type='EDGE_SPLIT')
bpy.ops.mira.wrap_object()
Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mira_tools\mi_wrap_master.py", line 61, in execute
    bpy.context.object.modifiers["EdgeSplit"].split_angle = 0
KeyError: 'bpy_prop_collection[key]: key "EdgeSplit" not found'
bpy.data.window_managers["WinMan"].addon_search = "machine"
bpy.data.window_managers["WinMan"].addon_search = "mach"
已保存偏好设置(preference have been saved)
bpy.ops.object.delete(use_global=False)
bpy.ops.object.modifier_add(type='EDGE_SPLIT')
bpy.ops.mira.wrap_object()
Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\mira_tools\mi_wrap_master.py", line 61, in execute
    bpy.context.object.modifiers["EdgeSplit"].split_angle = 0
KeyError: 'bpy_prop_collection[key]: key "EdgeSplit" not found'
****

![error](https://github.com/mifth/mifthtools/assets/140043294/f7e20eb2-d1f6-438a-b694-16eb0fa5ecc1)

it will copy a new mesh with edgesplit modifier which haven't been applied

**Comment by YHOOOO996** [comment]
if i recover preference setting to default, it work,so i guess maybe other addon cause this

**Comment by mifth** [comment]
@YHOOOO996 thank you so much for your report. I've fixed the bug in latest. Please, get latest files.
