### ISSUE TITLE
Mira Tools error on 2.83 Blender

### ISSUE THREAD

**Issue by stjepanovic** [mifth/mifthtools#39]
![image](https://github.com/mifth/mifthtools/assets/6437206/83e445e6-d9c2-4c22-b190-d34b8e910be3)

There are several errors
![Screenshot 2024-02-27 002328](https://github.com/mifth/mifthtools/assets/6437206/a4a799fb-e8a8-4f15-8866-9ef9f4e4c0c7)

**Comment by stjepanovic** [comment]
Do you have an old version of mira tools in your repository? I would really
appreciate it. Thank you!

**Comment by mifth** [comment]
@stjepanovic have a try this version. https://github.com/mifth/mifthtools/archive/29cd4d50573964bbad09fa61d1384d4add8b0720.zip
