### ISSUE TITLE
Feature request- option to link all handles when selecting multiple loops to make deformation uniformly

### ISSUE THREAD

**Issue by rajq123** [mifth/mifthtools#40]
![image](https://github.com/mifth/mifthtools/assets/57880269/87f30b0d-2fc6-4c01-8558-242c209ba3d7)
I just pointed out 2nd number for example but this option should link all the respective nodes of all loops.
- currently we have to manually figure out the position to have same deformation in all multiple loops. which is not precise as well.

- with proposed solution we can shape multiple loops at the same time with same tranformation to have uniformity.

**Comment by mifth** [comment]
I guess you can do this with Additive selection or box/circle tools.

![image](https://github.com/mifth/mifthtools/assets/2251298/5fac2c9e-c292-47ea-a5ea-55bd1de0d64b)

**Comment by rajq123** [comment]
Can you combine the space function of loop tools with it so we can also space out distance evenly at the same time...
