### ISSUE TITLE
I can make PR for converting Mira Tools for B 4.2

### ISSUE THREAD

**Issue by JoseConseco** [mifth/mifthtools#41]
Hi, I  love  Linear Deformer from Mira Tool. if u want I could make PR for making Mira Tool  work as extension compatible with B 4.2. Let me know if u would accept it. I know u use auto_load.py - this will need to be fixed to make it work in b 4.2 to... But it is quite easy.

**Comment by mifth** [comment]
Hi Jose,
Sure, go ahead. thank you so much.

**Comment by mifth** [comment]
Btw, as far as I remember the auto_load.py was written by you. All regards to you.

**Comment by JoseConseco** [comment]
it was actually written by https://code.blender.org/author/jacqueslucke/  - main geo nodes dev.   Will try to make PR when  I have bit of time.

**Comment by mifth** [comment]
I've just installed Blender 4.2.1 and Mira Tools work fine. I'm closing the issue.

![image](https://github.com/user-attachments/assets/e822b3dd-abac-477c-8772-9f359ad740f5)
